In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['France' 55.0 65000.0]
 ['Spain' 47.0 45000.0]
 ['Germany' 20.0 55000.0]
 ['Spain' 48.0 61000.0]
 ['Germany' 30.0 nan]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'No']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61538.46153846154]
 ['France' 35.0 58000.0]
 ['Spain' 39.214285714285715 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['France' 55.0 65000.0]
 ['Spain' 47.0 45000.0]
 ['Germany' 20.0 55000.0]
 ['Spain' 48.0 61000.0]
 ['Germany' 30.0 61538.46153846154]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61538.46153846154]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 39.214285714285715 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 55.0 65000.0]
 [0.0 0.0 1.0 47.0 45000.0]
 [0.0 1.0 0.0 20.0 55000.0]
 [0.0 0.0 1.0 48.0 61000.0]
 [0.0 1.0 0.0 30.0 61538.46153846154]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 1 1 1 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=1)

In [12]:
print(x_train)

[[0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 48.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 30.0 61538.46153846154]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 20.0 55000.0]
 [0.0 0.0 1.0 47.0 45000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 39.214285714285715 52000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 55.0 65000.0]
 [0.0 1.0 0.0 40.0 61538.46153846154]]


In [14]:
print(y_train)

[1 1 0 0 1 0 1 1 1]


In [15]:
print(y_test)

[0 1 0 0 0 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 0.0 1.0 -1.0685630178313883 -1.1854295082397188]
 [0.0 0.0 1.0 1.0573149860647417 -0.015385198030365671]
 [1.0 0.0 0.0 0.6523858424654789 0.9746522952237023]
 [0.0 1.0 0.0 -0.7648661601319411 0.033078175765288056]
 [1.0 0.0 0.0 -0.056240158833231114 0.5246352528354896]
 [0.0 1.0 0.0 1.2597795578643731 1.9646897884777703]
 [0.0 1.0 0.0 -1.7771890191300983 -0.5554056488962209]
 [0.0 0.0 1.0 0.956082700164926 -1.4554397336726463]
 [1.0 0.0 0.0 -0.25870473063286253 -0.28539542346329333]]


In [18]:
print(x_test)

[[0.0 0.0 1.0 0.0449921270665846 -0.015385198030365671]
 [1.0 0.0 0.0 1.0573149860647417 1.6046761545672001]
 [0.0 0.0 1.0 0.16791704565921806 -0.8254158743291486]
 [0.0 1.0 0.0 -0.7648661601319411 -0.6454090573738634]
 [1.0 0.0 0.0 1.7659409873634517 0.34462843588020453]
 [0.0 1.0 0.0 0.24745669886621602 0.033078175765288056]]
